//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025경기_1과제.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class movie
    {
        public movie()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public int mno { get; set; }
        public string mname { get; set; }
        public int gno { get; set; }
        public string introduction { get; set; }
        public string director { get; set; }
        public string actor { get; set; }
        public System.DateTime sdate { get; set; }
        public System.DateTime edate { get; set; }
        public int rtime { get; set; }
        public int tno { get; set; }
        public int ano { get; set; }
    
        public virtual age age { get; set; }
        public virtual genre genre { get; set; }
        public virtual theater theater { get; set; }
        public virtual ICollection<reservation> reservation { get; set; }
    }
}
