//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025경기_1과제.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public reservation()
        {
            this.review = new HashSet<review>();
        }
    
        public int rno { get; set; }
        public int uno { get; set; }
        public int mno { get; set; }
        public System.DateTime rdate { get; set; }
        public System.TimeSpan rtime { get; set; }
        public Nullable<int> adult { get; set; }
        public Nullable<int> teenager { get; set; }
        public Nullable<int> senior { get; set; }
        public string seat { get; set; }
        public Nullable<int> coupon { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual movie movie { get; set; }
        public virtual users users { get; set; }
        public virtual ICollection<review> review { get; set; }
    }
}
