//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025광주_1과제.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobposting
    {
        public jobposting()
        {
            this.applicationemployment = new HashSet<applicationemployment>();
        }
    
        public int jp_no { get; set; }
        public string jp_title { get; set; }
        public int jt_no { get; set; }
        public int l_no { get; set; }
        public int jp_sc { get; set; }
        public int o_no { get; set; }
        public int jp_situation { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime end_date { get; set; }
        public System.DateTime write_date { get; set; }
        public int c_no { get; set; }
        public int e_no { get; set; }
    
        public virtual ICollection<applicationemployment> applicationemployment { get; set; }
        public virtual company company { get; set; }
        public virtual education education { get; set; }
        public virtual jobtype jobtype { get; set; }
        public virtual location location { get; set; }
        public virtual occupation occupation { get; set; }
    }
}
