//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025광주_1과제.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class placementEntities : DbContext
    {
        public placementEntities()
            : base("name=placementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<applicationemployment> applicationemployment { get; set; }
        public DbSet<comment> comment { get; set; }
        public DbSet<company> company { get; set; }
        public DbSet<education> education { get; set; }
        public DbSet<employment> employment { get; set; }
        public DbSet<jobposting> jobposting { get; set; }
        public DbSet<jobtype> jobtype { get; set; }
        public DbSet<location> location { get; set; }
        public DbSet<occupation> occupation { get; set; }
        public DbSet<searchhistory> searchhistory { get; set; }
        public DbSet<selfintroduction> selfintroduction { get; set; }
        public DbSet<user> user { get; set; }
    }
}
