//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025광주_1과제_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int cm_no { get; set; }
        public string cm_explan { get; set; }
        public int si_no { get; set; }
        public int u_no { get; set; }
        public System.DateTime cm_date { get; set; }
    
        public virtual selfintroduction selfintroduction { get; set; }
        public virtual user user { get; set; }
    }
}
