//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025광주_1과제_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        public company()
        {
            this.employment = new HashSet<employment>();
            this.jobposting = new HashSet<jobposting>();
            this.searchhistory = new HashSet<searchhistory>();
        }
    
        public int c_no { get; set; }
        public string c_name { get; set; }
        public string c_id { get; set; }
        public string c_pw { get; set; }
        public int c_information { get; set; }
    
        public virtual ICollection<employment> employment { get; set; }
        public virtual ICollection<jobposting> jobposting { get; set; }
        public virtual ICollection<searchhistory> searchhistory { get; set; }
    }
}
