//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025광주_1과제_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobtype
    {
        public jobtype()
        {
            this.jobposting = new HashSet<jobposting>();
        }
    
        public int jt_no { get; set; }
        public string jt_name { get; set; }
    
        public virtual ICollection<jobposting> jobposting { get; set; }
    }
}
