//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2025광주_1과제_2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.applicationemployment = new HashSet<applicationemployment>();
            this.comment = new HashSet<comment>();
            this.employment = new HashSet<employment>();
            this.searchhistory = new HashSet<searchhistory>();
            this.selfintroduction = new HashSet<selfintroduction>();
        }
    
        public int u_no { get; set; }
        public string u_name { get; set; }
        public string u_id { get; set; }
        public string u_pw { get; set; }
        public string u_sc { get; set; }
        public string u_si { get; set; }
        public int u_situation { get; set; }
        public int e_no { get; set; }
        public int o_no { get; set; }
    
        public virtual ICollection<applicationemployment> applicationemployment { get; set; }
        public virtual ICollection<comment> comment { get; set; }
        public virtual education education { get; set; }
        public virtual ICollection<employment> employment { get; set; }
        public virtual occupation occupation { get; set; }
        public virtual ICollection<searchhistory> searchhistory { get; set; }
        public virtual ICollection<selfintroduction> selfintroduction { get; set; }
    }
}
